Repository ethersphere/bee-js, pull requests merged in 2021-03, with the labels that each got.

#160 chore: release 0.5.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending, pull-request

#169 docs: update README
  README.md
Labels: pull-request

#173 test: feed manifest creation and retrieval
  test/bee-class.spec.ts
Labels: pull-request

#181 test: run tests on Bee 0.5.2
  .github/workflows/ci.yaml
  test/bee.sh
Labels: pull-request

#187 chore: customize BeeWorker labels names
  .github/config.yaml
Labels: pull-request

#189 refactor!: correct getChequebookBalance spelling (remove extra u)
  src/bee-debug.ts
  src/modules/debug/chequebook.ts
  test/modules/debug/chequebook.spec.ts
Labels: type:pull-request

#194 fix: no ethereum prefix for custom signers
  src/chunk/signer.ts
  src/chunk/soc.ts
  test/chunk/signer.spec.ts
Labels: type:pull-request

#193 ci: separated browser and nodejs tests
  .github/workflows/ci.yaml
  .github/workflows/tests.yaml
  README.md
Labels: type:pull-request

#198 test(feed): increase flaky feed tests timeout
  test/bee-class.spec.ts
  test/utils.ts
Labels: type:pull-request

#192 ci(release-please): before 1.x any breaking changes will bump minor
  .github/workflows/release_github.yaml
Labels: type:pull-request

#180 fix(pss): subscribe in browsers, removed readable in browsers
  jest-puppeteer.config.js
  package-lock.json
  package.json
  src/bee.ts
  src/utils/data.browser.ts
  src/utils/data.ts
  test/bee-class.browser.spec.ts
  test/utils.ts
Labels: type:pull-request

#203 fix: strip trailining slash in node url
  package.json
  src/bee-debug.ts
  src/bee.ts
  src/index.ts
  src/utils/url.ts
  test/bee-class.browser.spec.ts
  test/bee-class.spec.ts
Labels: type:pull-request

#206 refactor: drop owner in favor of ethaddress
  src/bee.ts
  src/chunk/owner.ts
  src/chunk/signer.ts
  src/chunk/soc.ts
  src/feed/index.ts
  src/utils/eth.ts
  test/bee-class.spec.ts
Labels: kind:refactor, type:pull-request

#199 chore: release 0.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending, type:pull-request

#213 feat!: hex string length support
  src/bee-debug.ts
  src/bee.ts
  src/chunk/signer.ts
  src/feed/index.ts
  src/feed/topic.ts
  src/modules/bytes.ts
  src/modules/collection.ts
  src/modules/feed.ts
  src/modules/file.ts
  src/types/index.ts
  src/utils/eth.ts
  src/utils/hex.ts
  test/bee-class.spec.ts
  test/bee.sh
  test/chunk/signer.spec.ts
  test/feed/index.spec.ts
  test/modules/collection.spec.ts
  test/modules/debug/chequebook.spec.ts
  test/modules/feed.spec.ts
  test/utils.ts
  test/utils/hex.spec.ts
Labels: type:pull-request

#221 chore: drop node v10
  README.md
  package.json
Labels: type:pull-request

#219 feat: data helpers for downloaded bytes
  src/bee.ts
  src/modules/bytes.ts
  src/modules/collection.ts
  src/modules/file.ts
  src/types/index.ts
  src/utils/bytes.ts
  test/utils/bytes.spec.ts
Labels: type:pull-request

#220 ci: use different node versions
  .github/workflows/tests.yaml
Labels: type:pull-request

#215 chore: simplify tsconfigs
  package-lock.json
  package.json
  src/types/webpack-bundle-analyzer/index.d.ts
  tsconfig.d.json
  tsconfig.json
  tsconfig.typedoc.json
  typedoc.json
Labels: type:pull-request

#222 chore: bump bee version
  .github/workflows/tests.yaml
  test/bee.sh
Labels: type:pull-request

#217 refactor(chequebook): added integer validation and BigInt as type
  src/bee-debug.ts
  src/feed/type.ts
  src/modules/debug/chequebook.ts
  src/utils/type.ts
  test/modules/debug/chequebook.spec.ts
  test/utils/type.spec.ts
Labels: type:pull-request

#207 feat: missing endpoints on Bee and BeeDebug class
  src/bee-debug.ts
  src/bee.ts
  src/modules/debug/connectivity.ts
  src/modules/debug/status.ts
  src/modules/status.ts
  src/types/debug.ts
  test/modules/debug/connectivity.spec.ts
  test/modules/debug/status.spec.ts
  test/modules/status.spec.ts
Labels: type:pull-request

#226 docs: update README example with helper function
  README.md
Labels: type:pull-request

#233 test: increased timeouts for tests testing failure and big files
  test/bee.sh
  test/feed/index.spec.ts
  test/modules/bytes.spec.ts
  test/modules/chunk.spec.ts
  test/modules/collection.spec.ts
  test/modules/feed.spec.ts
  test/modules/file.spec.ts
  test/modules/pinning.spec.ts
  test/utils.ts
Labels: type:pull-request

#229 ci: using specific version of the bee node for tests
  .github/workflows/tests.yaml
Labels: type:pull-request

#234 refactor!: isEthAddress to isHexEthAddress
  src/utils/eth.ts
  test/utils/eth.spec.ts
Labels: kind:refactor, type:pull-request

#223 feat: improved signer interface and validation
  src/chunk/signer.ts
  src/chunk/soc.ts
  src/utils/bytes.ts
  test/chunk/signer.spec.ts
  test/utils.ts
Labels: need:documentation, type:pull-request

#232 fix: adding string type and assertions to Reference on API
  src/bee.ts
  src/modules/pinning.ts
  src/utils/hex.ts
  src/utils/type.ts
Labels: type:pull-request

#228 feat!: replaced `getPssPublicKey` with `getNodeAddresses`
  src/bee-debug.ts
  test/bee-class.browser.spec.ts
  test/bee-class.spec.ts
Labels: type:pull-request

#224 feat: default signer on bee instance
  src/bee.ts
  src/chunk/signer.ts
  src/types/index.ts
  test/bee-class.spec.ts
  test/chunk/signer.spec.ts
  test/chunk/soc.spec.ts
  test/feed/index.spec.ts
Labels: need:documentation

#239 refactor: move hash module to util folder
  src/chunk/bmt.ts
  src/chunk/signer.ts
  src/chunk/soc.ts
  src/feed/index.ts
  src/feed/topic.ts
  src/utils/hash.ts
Labels: type:pull-request

#238 refactor: split soc and cac tests and drop verify*
  src/chunk/cac.ts
  src/chunk/soc.ts
  test/chunk/cac.spec.ts
  test/chunk/soc.spec.ts
Labels: type:pull-request

#230 feat: ethereum wallet signer utility
  src/utils/eth.ts
  test/utils/eth.spec.ts
Labels: type:pull-request

#240 feat: add supported bee version to package.json
  package.json
  src/bee-debug.ts
  src/index.ts
  src/modules/debug/status.ts
  test/modules/debug/status.spec.ts
Labels: type:pull-request

#235 feat: expose external types
  src/bee.ts
  src/chunk/signer.ts
  src/chunk/soc.ts
  src/feed/index.ts
  src/feed/topic.ts
  src/modules/feed.ts
  src/types/index.ts
  src/utils/eth.ts
  test/feed/index.spec.ts
Labels: type:pull-request

#218 chore: release 0.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending, type:pull-request

#241 fix: correct package.json types path
  package.json
Labels: type:pull-request

#242 chore: release 0.7.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending, type:pull-request
