Repository ethersphere/bee-js, pull requests merged in 2024-10, with the labels that each got.

#953 chore(master): release 8.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: type:pull-request, autorelease: pending

#941 feat: add head bytes endpoint
  src/bee.ts
  src/modules/bytes.ts
  src/types/index.ts
  test/integration/bee-class.spec.ts
Labels: type:pull-request

#957 chore(master): release 8.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#963 chore(master): release 8.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
